{{- if .Values.sonarqube.service }}
{{- with .Values.sonarqube.service }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "sonarqube.fullname" $ }}
  labels: {{ include "sonarqube.labels" $ | nindent 4 }}
spec:
  selector: {{ include "sonarqube.selectorLabels" $ | nindent 4 }}
  type: {{ .type }}
  {{- if .ports }}
  ports: {{ toYaml .ports | nindent 4 }}
  {{- end }}
{{- end }}
{{- end }}
