apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "sonarqube.fullname" $ }}
  labels:
    {{- include "sonarqube.labels" $ | nindent 4 }}
spec:
  {{- with .Values.sonarqube }}
  {{- $sonarqube := . }}
  replicas: {{ .replicaCount | default 1 }}
  strategy:
    type: Recreate
  selector:
    matchLabels:
      {{- include "sonarqube.selectorLabels" $ | nindent 6 }}
  template:
    metadata:
      {{- if .annotations }}
      annotations:
        {{- toYaml .annotations | nindent 8 }}
      {{- end }}
      labels:
        {{- include "sonarqube.selectorLabels" $ | nindent 8 }}
    spec:
      containers:
        {{- with .containers.sonarqube }}
        - name: {{ $.Chart.Name }}
          {{- with .image }}
          image: "{{ .repository }}:{{ .tag | default $.Chart.AppVersion }}"
          imagePullPolicy: {{ .pullPolicy | default "IfNotPresent" }}
          {{- end }}
          {{- if .env }}
          env:
            {{- toYaml .env | nindent 12 }}
          {{- end }}
          {{- if $sonarqube.service }}
          ports:
            {{- range $sonarqube.service.ports }}
            - containerPort: {{ .targetPort }}
              name: {{ .name }}
              protocol: {{ .protocol }}
            {{- end }}
          {{- end }}
          livenessProbe:
            httpGet:
              path: /api/system/status
              port: {{ .port | default 9000 }}
              scheme: HTTP
            initialDelaySeconds: 60
            periodSeconds: 20
            timeoutSeconds: 2
            successThreshold: 1
            failureThreshold: 5
          readinessProbe:
            httpGet:
              path: /api/system/status
              port: {{ .port | default 9000 }}
              scheme: HTTP
            initialDelaySeconds: 30
            periodSeconds: 15
            timeoutSeconds: 2
            successThreshold: 1
            failureThreshold: 3
          {{- if .resources }}
          resources:
            {{- toYaml .resources | nindent 12 }}
          {{- end }}
          {{- if .volumeMounts }}
          volumeMounts:
            {{- toYaml .volumeMounts | nindent 12 }}
          {{- end }}
        {{- end }}
      hostname: {{ .hostname | default "sonarqube" }}
      restartPolicy: Always
      {{- if .volumes }}
      volumes:
        {{- toYaml .volumes | nindent 8 }}
      {{- end }}
  {{- end }}
